### ISSUE TITLE
AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by EHAndrew** [LXGaming/Authentication#1]
Still works on 1.13.2, however it's had this AsyncPlayerChatEvent issue for a while now. It's not a huge issue, but it'd be nice to be rid of it. Otherwise, this plugin continues to work despite all the changes through the years. It only happens when a player tries to talk before they've used /accept

```yaml
[13:14:32] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Authentication v1.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-492]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1705) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1620) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:707) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.performCommand(CraftPlayer.java:448) ~[patched_1.13.2.jar:git-Paper-492]
	at io.github.lxgaming.authentication.events.PlayerChatEvent.onPlayerChatEvent(PlayerChatEvent.java:37) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
	... 11 more
```

**Comment by LXGaming** [comment]
Update is available on:
**Github**: https://github.com/LXGaming/Authentication/releases/tag/v1.0.1
**Spigot**: https://www.spigotmc.org/resources/authentication.15891/update?update=259249

**Comment by EHAndrew** [comment]
Thanks so much!
